web/javamoney-tradingapp/src/main/java/net/java/javamoney/examples/tradingapp/web/PortfolioController.java
/*
 * JSR 354 Stock-Trading Example
 * Copyright 2005-2013, Werner Keil and individual contributors by the @author tag. 
 * See the copyright.txt in the distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,  
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.java.javamoney.examples.tradingapp.web;

import static net.java.javamoney.examples.tradingapp.Constants.MARKET;
import static net.java.javamoney.examples.tradingapp.Constants.MODEL;
import static net.java.javamoney.examples.tradingapp.Constants.PORTFOLIO;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.StringTokenizer;

import javax.measure.unit.UnitFormat;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.java.javamoney.examples.tradingapp.business.Market;
import net.java.javamoney.examples.tradingapp.business.Portfolio;
import net.java.javamoney.examples.tradingapp.quotes.QuoteManager;
import net.neurotech.quotes.Quote;
import net.neurotech.quotes.QuoteException;
import net.neurotech.quotes.QuoteFactory;

import org.apache.log4j.Logger;
import org.jscience.economics.money.Currency;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;


public class PortfolioController implements Controller {
	/**
	 * Logger for this class
	 */
	private static final Logger logger = Logger
			.getLogger(PortfolioController.class);
    
    private Market market;
	private net.java.javamoney.examples.tradingapp.business.Portfolio portfolio;
    private static QuoteFactory quoteFactory;
    private Properties props;
    
    public PortfolioController(Portfolio portfolio, Market market) {
        this.props = new Properties(); // TODO i18n, use ResourceBundle or Messages where possible
    	this.market = market;
    	this.portfolio = portfolio;        
        quoteFactory = QuoteManager.getQuoteFactory();
        
        try {
        	InputStream in = PortfolioController.class.getResourceAsStream 
        	 ("/currency.properties");
        	props.load(in);
        	
        	if (Currency.getReferenceCurrency() != null) {
        		labelCurrency(Currency.getReferenceCurrency());
        	}       	
        } catch (IOException ie) {
        	logger.warn("Error loading properties", ie); 
        }
    }

    public ModelAndView handleRequest(HttpServletRequest request,
            HttpServletResponse response) {
        Map<String, Object> model = new HashMap<String, Object>();
        
        String m = null;
        Object o;
        Enumeration e = request.getParameterNames();
        while (e.hasMoreElements()) {        	
        	o = e.nextElement();
        	//logger.info("Param: " + o);
        	if (String.valueOf(o).equals(MODEL)) {
        		o = request.getParameter(MODEL);
	        	if (o instanceof Map) {
	        		//logger.info("It's a Map");
	        		model = (Map)o;        		
	        	}
        	} else if (String.valueOf(o).equals(MARKET)) {
        		m = request.getParameter(MARKET);
        	}
        }
        
        if (m != null && m.length()>0) {
        	String mDetails = this.market.getKnownMarkets().get(m);
        	logger.info("Market: " + m + "=" + mDetails);
        	market.setSymbol(m);        	
        	//model.put(MARKET, m);
        	 
        	String cSymbol = null;
        	String mName = null;
        	StringTokenizer st = new StringTokenizer(mDetails, ";");
        	while (st.hasMoreElements()) {
        		if (mName == null) {
        			mName = st.nextToken();
        		} else {
	        		if (cSymbol == null) {
	        			cSymbol = st.nextToken();
	        		}
        		}
        	}
        	if (mName != null) {
        		market.setName(mName);
        	}
        	if (cSymbol != null) {
        		Currency curr = new Currency(cSymbol);
        		
        		// TODO retrieve this from Yahoo Service similar to quotes, or 354 style ExchangeRateProvider
        		Object oRate = market.getCurrencyExchangeRates().get(cSymbol);
        		if (oRate != null) {
        			Number exchangeRate;
        			if (oRate instanceof Number) {
        				exchangeRate = (Number)oRate;
        			} else {
        				try {
        					exchangeRate = Double.parseDouble(String.valueOf(oRate));
        				} catch (NumberFormatException nfe) {
        					logger.warn("Error during currency conversion", nfe);
        					exchangeRate = 0;
        				}
        			}
        			logger.info(exchangeRate);
        			curr.setExchangeRate(exchangeRate.doubleValue());
        		} else {
        			logger.warn("Could not find exchange rate for " + curr);
        			curr.setExchangeRate(0); // TODO kind of dodgy, should throw exception or something?
        		}
        		//curr.setExchangeRate(1.4);
        		
        		labelCurrency(cSymbol, curr);
        		//Currency.setReferenceCurrency(curr);
        		portfolio.setCurrency(curr);
        		
        		// TODO portfolio should directly store market!
        		market.setCurrency(curr);        		
        	}
        }
        List<PortfolioItemBean> portfolioItems = getPortfolioItems();
        model.put(MARKET, market);
        model.put("currency", portfolio.getCurrency());
        model.put("cash", portfolio.getCash() + "");
        model.put("amount", portfolio.getAmount());
        model.put("amountLocal", portfolio.getAmount().to(portfolio.getCurrency()));
        model.put("portfolioItems", portfolioItems);

        return new ModelAndView(PORTFOLIO, MODEL, model);
    }

    private void labelCurrency(String symbol, Currency curr) {
		//String label = market.getCurrencyLabels().get(cSymbol);
		String label = props.getProperty(symbol, "");
		if (label != null && label.length()>0) {
			UnitFormat.getInstance().label(curr, label);
		}
    }
    
    private void labelCurrency(Currency curr) {
    	labelCurrency(curr.getCode(), curr);
    }
    
    private List<PortfolioItemBean> getPortfolioItems() {
        List<PortfolioItemBean> portfolioItems = new ArrayList<PortfolioItemBean>();

        Iterator symbolIter = portfolio.getSymbolIterator();
        //QuoteFactory quoteFactory = new QuoteFactory();
         
        while (symbolIter.hasNext()) {
            String symbol = (String) symbolIter.next();

            int shares = portfolio.getNumberOfShares(symbol);            

            Quote quote = null;

            try {
                quote = quoteFactory.getQuote(symbol);
            } catch (QuoteException e) {
            	logger.warn("Error during quote", e);
                quote = new Quote(this.getClass().getName()) {
                };
            }

            PortfolioItemBean portfolioItem = new PortfolioItemBean(portfolio);
            portfolioItem.setSymbol(symbol);
            portfolioItem.setShares(shares);
            portfolioItem.setQuote(quote);
            portfolioItem.setCurrentValue(shares * quote.getValue());
            portfolioItem.setGainLoss(shares * quote.getPctChange());
            portfolioItems.add(portfolioItem);
        }
        return portfolioItems;
    }
}

web/javamoney-tradingapp/src/main/java/net/java/javamoney/examples/tradingapp/web/PortfolioItemBean.java
/*
 * JSR 354 Stock-Trading System
 * Copyright 2005-2013, Werner Keil and individual contributors by the @author tag. 
 * See the copyright.txt in the distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,  
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.java.javamoney.examples.tradingapp.web;

import org.jscience.economics.money.Currency;
import org.jscience.economics.money.Money;
import org.jscience.physics.amount.Amount;


import net.java.javamoney.examples.tradingapp.business.Portfolio;
import net.neurotech.quotes.Quote;

public class PortfolioItemBean {
    private Currency currency;
    
	private String symbol;

    private int shares;

    private Quote quote;

    private Amount<Money> currentAmount;
    
    private double gainLoss;
    
    protected PortfolioItemBean(Currency curr) {
    	this.currency = curr;
    }
    
    public PortfolioItemBean(Portfolio parent) {
    	this(parent.getCurrency());
    }
    
    public int getShares() {
        return shares;
    }

    public void setShares(int quantity) {
        this.shares = quantity;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public double getCurrentValue() {
        return currentAmount.doubleValue(currency);
    }

    public void setCurrentValue(double currentValue) {
        //this.currentValue = currentValue;
    	this.currentAmount = Amount.valueOf(currentValue, Currency.getReferenceCurrency());
    }

    public Quote getQuote() {
        return quote;
    }

    public void setQuote(Quote quote) {
        this.quote = quote;
    }

	/**
	 * @return the Quote value as Amount
	 */
	public Amount<Money> getQuoteAmount() {
		return Amount.valueOf(quote.getValue(), Currency.getReferenceCurrency());
	}
    
	/**
	 * @return the Quote change as Amount
	 */
	public Amount<Money> getQuoteChangeAmount() {
		return Amount.valueOf(quote.getChange(), Currency.getReferenceCurrency());
	}

    public double getGainLoss() {
        return gainLoss;
    }

    public void setGainLoss(double valueChange) {
        this.gainLoss = valueChange;
    }
    
	/**
	 * @return Gain or Loss as Amount
	 */
	public Amount<Money> getGainLossAmount() {
		return Amount.valueOf(gainLoss, Currency.getReferenceCurrency());
	}
	
	/**
	 * @return Quote Opening Price as Amount
	 */
	public Amount<Money> getQuoteOpenAmount() {
		return Amount.valueOf(quote.getOpenPrice(), Currency.getReferenceCurrency());
	}

	/**
	 * @return the currentAmount
	 */
	public Amount<Money> getCurrentAmount() {
		return currentAmount;
	}

	/**
	 * @return the currentAmount in local Currency
	 */
	public Amount<Money> getCurrentAmountLocal() {
		return currentAmount.to(currency);
	}
	
	/**
	 * @param currentAmount the currentAmount to set
	 */
	public void setCurrentAmount(Amount<Money> currentAmount) {
		this.currentAmount = currentAmount;
	}

	/**
	 * @return the currency
	 */
	public Currency getCurrency() {
		return currency;
	}

	/**
	 * @param currency the currency to set
	 */
	public void setCurrency(Currency currency) {
		this.currency = currency;
	}
}

web/javamoney-tradingapp/src/main/webapp/WEB-INF/jsp/include.jsp
<%@ page   session="false"%>
<%@ page   contentType="text/html; charset=UTF-8"%>
<%@ page   pageEncoding="UTF-8" %>
<%@ taglib prefix="core" uri="http://java.sun.com/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>
<%@ taglib prefix="str" uri="http://jakarta.apache.org/taglibs/string-1.1" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<link href="<%=request.getContextPath ()%>/css/people.css" rel="stylesheet" type="text/css"/>

web/javamoney-tradingapp/src/main/webapp/WEB-INF/jsp/logon.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<%@page import="net.java.javamoney.examples.tradingapp.Constants"%>
<%--	
	Enumeration e =	application.getAttributeNames();
	while (e.hasMoreElements()) {
		//System.out.println("Attrib: " + e.nextElement());
		e.nextElement();
	}
	//System.out.println("Servlet: " + config.getServletName());
	System.out.println("Servlet Info: " + getServletInfo());
	//this.g
	e = config.getInitParameterNames();
	while (e.hasMoreElements()) {
		System.out.println("InitParam: " + e.nextElement());
	}
--%>

<html>
<head>
	<%-- META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8" / --%>
	<title><%= Constants.APP_TITLE %> Sign In</title>
	<script language=javascript src="<%=request.getContextPath ()%>/scripts/controls.js">
	</script>
	</head>
<body class="loginbg" onload="initSkin()">
<h1>Welcome to the <%= Constants.APP_TITLE %></h1>
<div class="SiteContainer SignIn">
	<h2 class="About">Sign In</h2>
	<br/>
	<div class=SignInForm id=Form>
		<fieldset>
			<form id=frmSignIn method="post">
				<%-- b><i>Please log in.</i></b --%>
				<br><br>
				<ul>
	  				<li>
						<label for="username">Username</label>
						<spring:bind path="credentials.username">
							<input class="textinput" type="text" 
						       name="username" 
						       value="<core:out value="${status.value}"/>"/>		
						</spring:bind>
						<spring:hasBindErrors name="credentials">
						<br>
						<span class="logintexterror">
						    <core:forEach items="${status.errorMessages}" var="error">
						    	<img align="middle" src="<%=request.getContextPath ()%>/images/message_error.gif" alt='Authentication Denied'>
						    	&nbsp;<core:out value="${error}"/><br/>
						    </core:forEach>
					    </span>
						<%-- core:out value="${status.errorMessage}"/ --%>
						</spring:hasBindErrors>
					</li>
					<li>
						<label for="password">Password</label>
						<spring:bind path="credentials.password">
						<input class="textinput" type="password" name="password" />
						</spring:bind>
			
						<spring:hasBindErrors name="credentials">
						<br>
						<span class="logintexterror">
							<core:forEach items="${status.errorMessages}" var="error">
						    	<img align="middle" src="<%=request.getContextPath ()%>/images/message_error.gif" alt='Authentication Denied'>
						    	&nbsp;<core:out value="${error}"/><br/>
						    </core:forEach>
						</span>
						</spring:hasBindErrors>
					</li>
					<li>
						<label for="market">Market</label>
						<spring:bind path="credentials.market">
						<select class="textinput" name="market">
							<option value="FRA">Frankfurt</option>
							<option value="LSE">London</option>
							<option value="NYSE">New York</option>
							<option value="TSE">Tokyo</option>
						</select>	
						</spring:bind>
					</li>
				</ul>
				<div class="Submit">
					<input type="submit" class="formButton" alignment="center" value="Proceed" title="Proceed" accesskey="p" onclick="form.submit();this.disabled=true;document.body.style.cursor = 'wait'; this.className='buttondisabled';">
					<!-- tr>
		       					<td class="loginbottom" height="10px" colspan="2">&nbsp;</td>
		     				</tr -->
   				</div>
			</form>
		</fieldset>
	</div>
</div>
</body>
</html>

web/javamoney-tradingapp/src/main/webapp/WEB-INF/jsp/portfolio.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<%--@ page import="net.java.javamoney.examples.tradingapp.web.LogHelper"--%>
<html>
<head>
	<%-- meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta http-equiv="encoding" content="UTF-8" / --%>
	<title>Portfolio</title>
</head>
<body>
<h1>Portfolio</h1>
<span class="logintextbold">Cash:</span> 
<%-- fmt:formatNumber value="${model.cash}" type="currency" / --%>
<core:out value="${model.amountLocal}"/>
&nbsp;
<span class="logintextbold">Market:</span> 
<core:out value="${model.market}"/>
<br/>
<br/>
<table border="1">
	<tr>
		<th>Symbol</th>
		<th>Company</th>
		<th>Price</th>
		<th>Change</th>
		<th>% Change</th>
		<th>Shares</th>
		<th>Open</th>
		<th>Volume</th>
		<th>Current Value <span class="required">*</span></th>
		<th>Gain/Loss</th>
	</tr>
	<core:forEach items="${model.portfolioItems}" var="stock">
	<tr>
		<td><str:upperCase><core:out value="${stock.symbol}"/></str:upperCase></td>
		<td><core:out value="${stock.quote.company}"/></td>
		<td>
			<%-- fmt:formatNumber value="${stock.quote.value}" type="currency" / --%>
			<core:out value="${stock.quoteAmount}"/>
		</td>
		<td>
			<core:choose>
				<core:when test="${stock.quote.change >= 0}">
					<%-- fmt:formatNumber value="${stock.quote.change}" type="currency" / --%>
					<core:out value="${stock.quoteChangeAmount}"/>
				</core:when>
				<core:otherwise>
					<font color="red">
						<%-- fmt:formatNumber value="${stock.quote.change}" type="currency" / --%>
						<core:out value="${stock.quoteChangeAmount}"/>
					</font>
				</core:otherwise>
			</core:choose>	
		</td>
		<td>
			<core:choose>
				<core:when test="${stock.quote.pctChange >= 0}">
					<fmt:formatNumber value="${stock.quote.pctChange}" type="percent" />
				</core:when>
				<core:otherwise>
					<font color="red">
						<fmt:formatNumber value="${stock.quote.pctChange}" type="percent" />
					</font>
				</core:otherwise>
			</core:choose>	
		</td>
		<td><fmt:formatNumber value="${stock.shares}"/></td>
		<td>
			<%-- fmt:formatNumber value="${stock.quote.openPrice}" type="currency" / --%>
			<core:out value="${stock.quoteOpenAmount}"/>
		</td>
		<td><fmt:formatNumber value="${stock.quote.volume}"/></td>
		<td>
			<%-- fmt:formatNumber value="${stock.currentValue}" type="currency" / --%>
			<core:out value="${stock.currentAmountLocal}"/>
		</td>
		<td>
			<core:choose>
				<core:when test="${stock.gainLoss >= 0}">
					<%-- fmt:formatNumber value="${stock.gainLoss}" type="currency" /--%>
					<core:out value="${stock.gainLossAmount}"/>
				</core:when>
				<core:otherwise>
					<font color="red">
						<%-- fmt:formatNumber value="${stock.gainLoss}" type="currency" / --%>
						<core:out value="${stock.gainLossAmount}"/>
					</font>
				</core:otherwise>
			</core:choose>	
		</td>
	</tr>
	</core:forEach>
</table>
<br/>
<span class="required">*</span> in local Currency<br/>
<br>
<a href="<core:url value="trade.htm"/>">Make a trade</a><br/>
<a href="<core:url value="logon.htm"/>">Log out</a>
<br>
</body>
</html>

web/javamoney-tradingapp/src/main/webapp/WEB-INF/jsp/trade-acknowledge.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<html>
<head><title>Successful Trade Acknowledgement</title></head>
<body>
<h1>Successful Trade Acknowledgement</h1>
<form method="post">

<table border="1">
	<tr>
		<td></td>
		<td><b>Symbol</b></td>
		<td><b>Shares</b></td>
	</tr>
	<tr>
		<td>
			<core:choose>
				<core:when test="${trade.buySell == true}">Bought</core:when>
				<core:otherwise>Sold</core:otherwise>
			</core:choose>
		</td>
		<td>
			<core:out value="${trade.symbol}"/>	
		</td>
		<td>
			<core:out value="${trade.shares}"/>	
		</td>
	</tr>
</table>

<h2>Your order was filled</h2>
    
</form>
<br>
<a href="<core:url value="portfolio.htm"/>">View Portfolio</a><br/>
<a href="<core:url value="logon.htm"/>">Log out</a>
<br>
</body>
</html>

web/javamoney-tradingapp/src/main/webapp/WEB-INF/jsp/trade-confirm.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<html>
<head><title>Trade Confirmation</title></head>
<body>
<h1>Trade Confirmation</h1>
<form method="post">

<table border="1">
	<tr>
		<td></td>
		<td><b>Symbol</b></td>
		<td><b>Shares</b></td>
	</tr>
	<tr>
		<td>
			<core:choose>
				<core:when test="${trade.buySell == true}">Buy</core:when>
				<core:otherwise>Sell</core:otherwise>
			</core:choose>
		</td>
		<td>
			<core:out value="${trade.symbol}"/>	
		</td>
		<td>
			<core:out value="${trade.shares}"/>	
		</td>
	</tr>
	<tr>
		<td colspan="3" align="center">
			<input type="submit" class="formButton" alignment="center" name="_finish" value="Execute Order">
			<input type="submit" class="formButton" alignment="center" name="_cancel" value="Cancel Order">
		</td>
	</tr>
</table>

    
</form>
<br>
<a href="<core:url value="logon.htm"/>">Log out</a>
<br>
</body>
</html>

web/javamoney-tradingapp/src/main/webapp/WEB-INF/jsp/trade.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<html>
<head>
	<title>Trade</title>
	<script language=javascript src="<%=request.getContextPath ()%>/scripts/controls.js">
	</script>
</head>
<body class="loginbg" onload="initSkin()">
<h1>Trade</h1>
<form method="post">

<!-- first bind on the object itself to display global errors - if available -->
<spring:bind path="trade.*">
	<span class="logintexterror">
	    <core:forEach items="${status.errorMessages}" var="error">
	    Error: <core:out value="${error}"/><br/>
	    </core:forEach>
    </span>
    <br/>
</spring:bind>

<table border="1">
	<tr>
		<th></th>
		<th class="logintop">Symbol</th>
		<th class="logintop">Shares</th>
	</tr>
	<tr>
		<td>
			<spring:bind path="trade.buySell">
			<input type="radio" 
			       name="buySell" 
			       value="true" 
			       <core:if test="${status.value}">checked</core:if> >
				Buy
			</input>
			<input type="radio" 
			       name="buySell" 
			       value="false" 
			       <core:if test="${! status.value}">checked</core:if> >
				Sell
			</input>
			</spring:bind>			
		</td>
		<td>
			<spring:bind path="trade.symbol">
			<input type="text" name="symbol" value="<core:out value="${status.value}"/>"/>
			</spring:bind>
		</td>
		<td>
			<spring:bind path="trade.shares">
			<input type="text" name="shares" value="<core:out value="${status.value}"/>"/>
			</spring:bind>
		</td>
	</tr>
	<tr>
		<td colspan="3" align="center"><input type="submit" class="formButton" alignment="center" name="_target1" value="Execute Order"></td>
	</tr>
</table>

    
</form>
<br>
<a href="<core:url value="portfolio.htm"/>">View Portfolio</a><br/>
<a href="<core:url value="logon.htm"/>">Log out</a>
<br>
</body>
</html>