web/jsf-money/src/main/java/javamoneyexamples/jsf/money/model/ExchangeBean.java
package javamoneyexamples.jsf.money.model;

import java.io.Serializable;

import javax.money.CurrencyUnit;
import javax.money.MonetaryAmount;
import javax.money.Monetary;

import org.javamoney.moneta.Money;

public class ExchangeBean implements Serializable {

	private static final long serialVersionUID = -4277622484280053995L;

	private Double value;
	
	private String coinFrom;
	
	private String coinTo;
	
	private MonetaryAmount result;
	

	public Double getValue() {
		return value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	public String getCoinFrom() {
		return coinFrom;
	}

	public void setCoinFrom(String coin) {
		this.coinFrom = coin;
	}

	public MonetaryAmount getResult() {
		return result;
	}

	public void setResult(MonetaryAmount result) {
		this.result = result;
	}
	
	

	public String getCoinTo() {
		return coinTo;
	}

	public void setCoinTo(String coinTo) {
		this.coinTo = coinTo;
	}

	public CurrencyUnit getCurrencyFrom() {
		return Monetary.getCurrency(coinFrom);
	}
	
	public CurrencyUnit getCurrencyTo() {
		return Monetary.getCurrency(coinTo);
	}

	public MonetaryAmount getMounetaryFrom() {
		return Money.of(value, getCurrencyFrom());
	}
	
}

web/jsf-money/src/main/java/javamoneyexamples/jsf/money/model/Product.java
package javamoneyexamples.jsf.money.model;

import java.io.Serializable;

import javax.money.MonetaryAmount;

public class Product implements Serializable {

	private static final long serialVersionUID = 1L;

	private String name;
	
	private MonetaryAmount money;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public MonetaryAmount getMoney() {
		return money;
	}

	public void setMoney(MonetaryAmount money) {
		this.money = money;
	}
	
	
	@Override
	public String toString() {
		return "name: " + name + " money: " + money;
	}

	public void clear() {
		name = "";
		money = null;
	}
	
}

web/jsf-money/src/main/java/javamoneyexamples/jsf/money/model/User.java
package javamoneyexamples.jsf.money.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.money.CurrencyUnit;
import javax.money.MonetaryAmount;
import javax.money.Monetary;

import org.javamoney.moneta.FastMoney;
import org.javamoney.moneta.function.MonetaryFunctions;

public class User implements Serializable {

	private static final CurrencyUnit CURRENCY = Monetary.getCurrency("USD");

	private static final long serialVersionUID = -4619662846488953817L;
	
	private List<Product> products = new ArrayList<>();

	public List<Product> getProducts() {
		return products;
	}

	public void addProduct(Product product) {
		Product copy = new Product();
		copy.setMoney(product.getMoney());
		copy.setName(product.getName());
		products.add(copy);
		product.clear();
	}
	
	public MonetaryAmount getSum() {
		return products.stream().map(Product::getMoney)
				.reduce(MonetaryFunctions.sum())
				.orElse(FastMoney.of(0, CURRENCY));
	}
	
	public MonetaryAmount getMin() {
		return products.stream().map(Product::getMoney)
				.reduce(MonetaryFunctions.min())
				.orElse(FastMoney.of(0, CURRENCY));
	}
	
	
	public MonetaryAmount getMax() {
		return products.stream().map(Product::getMoney)
				.reduce(MonetaryFunctions.max())
				.orElse(FastMoney.of(0, CURRENCY));
	}
	
	public int getCount() {
		return products.size();
	}
	
	public MonetaryAmount getAverage() {
		return products.stream().map(Product::getMoney)
				.collect(MonetaryFunctions.summarizingMonetary(CURRENCY))
				.getAverage();
	}

	@Override
	public String toString() {
		return products.toString();
	}
	
}

web/jsf-money/src/main/java/javamoneyexamples/jsf/money/controller/ExchangeMB.java
package javamoneyexamples.jsf.money.controller;

import java.util.List;

import javamoneyexamples.jsf.money.exchange.ExchangeType;
import javamoneyexamples.jsf.money.model.ExchangeBean;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.money.MonetaryAmount;
import javax.money.convert.CurrencyConversion;
import javax.money.convert.ExchangeRateProvider;

@ViewScoped
@ManagedBean
public class ExchangeMB {

	@Inject
	private ExchangeBean bean;
	
	@Inject
	private ExchangeRateProvider provider;
	
	public List<String> getCoins() {
		return ExchangeType.getCoins();
	}
	
	public void exchange() {
		CurrencyConversion currencyConversion = provider.getCurrencyConversion(bean.getCurrencyTo());
		MonetaryAmount result = currencyConversion.apply(bean.getMounetaryFrom());
		bean.setResult(result);
	}

	public ExchangeBean getBean() {
		return bean;
	}

	public void setBean(ExchangeBean bean) {
		this.bean = bean;
	}
	
	
	
	
}

web/jsf-money/src/main/java/javamoneyexamples/jsf/money/controller/ProductMB.java
package javamoneyexamples.jsf.money.controller;

import java.io.Serializable;

import javamoneyexamples.jsf.money.model.Product;
import javamoneyexamples.jsf.money.model.User;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;


@SessionScoped
@Named
public class ProductMB implements Serializable {

	private static final long serialVersionUID = -8303484031079724876L;

	@Inject
	private Product product;
	
	@Inject
	private User user;

	public Product getProduct() {
		return product;
	}

	public User getUser() {
		return user;
	}
	
	
	public void add(){
		user.addProduct(product);
		System.out.println("Ok");
	}
	
}

web/jsf-money/src/main/webapp/exchange.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html">
	<h:head>
		<f:facet name="first">
			<meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
			<title>MoneyApi JSF example</title>
		</f:facet>
	</h:head>

	<h:body>
	 <p:panel id="basic" style="margin-bottom:20px" header="Exchange Rate">
		<h:form id="form">
			<h:panelGrid columns="3">
				<p:outputLabel  value="Coin from: " />
				<p:selectOneMenu  value="#{exchangeMB.bean.coinFrom}">
					<f:selectItems value="#{exchangeMB.coins}" />
				</p:selectOneMenu>
				<p:inputText id="valueInput" value="#{exchangeMB.bean.value}"  required="true"/>
				
				<p:outputLabel  value="Coin to: " />
				<p:selectOneMenu  value="#{exchangeMB.bean.coinTo}">
					<f:selectItems value="#{exchangeMB.coins}" />
				</p:selectOneMenu>
			</h:panelGrid>
			<div  style="margin-top: 20px"></div>
			<p:commandButton value="Exchange Rate" update="form" actionListener="#{exchangeMB.exchange}" styleClass="ui-priority-primary" />
			<div  style="margin-top: 60px"></div>
			
			<h3>The result is: <h:outputText value="#{exchangeMB.bean.result}" converter="outMonetaryAmount" /> </h3>
		</h:form>
		<h:form >
			<h:commandLink value="Back" action="index" />
		</h:form>
	</p:panel>	
	</h:body>
</f:view>
</html>

web/jsf-money/src/main/webapp/index.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html">
	<h:head>
		<f:facet name="first">
			<meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
			<title>MoneyApi JSF example</title>
		</f:facet>
	</h:head>

	<h:body>
	 
		<h:form id="form">
		<p:panel id="basic" header="JSF with moneyAPI" style="margin-bottom:20px">
			<h:panelGrid columns="1">
				<h:column>
					<p>Example using JSF with moneyAPI, with two simple samples.</p>
						<ul>
							<li>The first one is a list of products, when an element was added the table informs the number of elements, the cheaper one, expensive one, the sum and the average of products.</li>
							<li>The last one it to do exchange rage from some currencies.</li>
						</ul>
				</h:column>		
				<h:commandLink value="List of Products" action="product" />
				<h:commandLink value="Exchange Rate" action="exchange" />
			</h:panelGrid>
			</p:panel>
		</h:form>
		
	</h:body>

</f:view>
</html>

web/jsf-money/src/main/webapp/product.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html">
	<h:head>
		<f:facet name="first">
			<meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
			<title>MoneyApi JSF example</title>
		</f:facet>
	</h:head>

	<h:body>
	<p:panel id="basic" header="Products List" style="margin-bottom:20px">
		<h:form id="form">
			<h:panelGrid columns="2">
				<p:outputLabel for="nameInput" value="Name: " />
				<p:inputText id="nameInput" value="#{productMB.product.name}"  required="true"/>
				<p:outputLabel for="moneyInput" value="Money: " />
				<p:inputText id="moneyInput" value="#{productMB.product.money}" required="true"	converter="defaultMonetaryAmount" />
			</h:panelGrid>
			<div  style="margin-top: 20px"></div>
			<p:commandButton value="Add Product" update="form" actionListener="#{productMB.add}" styleClass="ui-priority-primary" />
			<div  style="margin-top: 20px"></div>

			<p:dataTable var="product" value="#{productMB.user.products}" style="margin-bottom: 20px">
				<p:column headerText="Name">
					<h:outputText value="#{product.name}"  />
				</p:column>

				<p:column headerText="Value">
					<h:outputText value="#{product.money}" converter="outMonetaryAmount" />
				</p:column>

				<f:facet name="footer">
        			In total there are #{productMB.user.count} products, with sum <h:outputText value="#{productMB.user.sum}" converter="outMonetaryAmount" />,
        			with max <h:outputText value="#{productMB.user.max}" converter="outMonetaryAmount" />, with min <h:outputText value="#{productMB.user.min}" converter="outMonetaryAmount" /> and
        			with average <h:outputText value="#{productMB.user.average}" converter="outMonetaryAmount" />.
    			</f:facet>
			</p:dataTable>
		</h:form>
		<h:form>
			<h:commandLink value="Back" action="index" style="margin-top: 20px;" />
		</h:form>
		</p:panel>
	</h:body>
</f:view>
</html>